### ISSUE TITLE
Left control buttons

### ISSUE THREAD

**Issue by digitologist** [JoshuaBatty/korgNanoKontrol2#1]
Found your library and works like a charm, except on the nano I was given the left control keys (track/cycle/marker/FF/RR/etc) weren't mapped to midiMessage.control 58+, instead they appeared as midiMessage.control = 0 but with midiMessage.pitch 1-11.

Not sure if this unit has been modified or if the library is out of date, but thanks for your work.

**Comment by JoshuaBatty** [comment]
No problem dude, thanks for pointing this out. I wont have a chance to check this out for a few weeks but ill update it when i do. Thanks for letting me know.

**Comment by digitologist** [comment]
My bad, I blew away its settings and they're back to what you had.  I'll close.  Finding this was a lifesaver in any case.
